env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
globals:
  JSX: readonly
settings:
  import/resolver:
    node: 
      extensions: [".js", ".jsx", ".ts", ".tsx"]
parserOptions:
  ecmaFeatures:
    jsx: true
    tsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: 
  arrow-body-style: [2, "as-needed"]
  arrow-spacing: 2
  camelcase: 1
  capitalized-comments: 2
  complexity: [2, 30]
  max-lines: [2, 110]
  max-depth: [2, 2]
  max-params: [1, 3]
  max-statements: [2, 20]
  max-statements-per-line: 2
  max-nested-callbacks: [2, 5] # default => 3
  max-len: [1, code: 150]
  no-unused-vars: 2
  no-alert: 2
  no-caller: 2
  no-console: 1
  no-empty-function: 2
  no-else-return: 2
  no-extend-native: 2
  no-new-wrappers: 2
  no-script-url: 2
  no-throw-literal: 2
  no-void: 2
  no-with: 2
  no-trailing-spaces: 2
  no-duplicate-imports: 2
  no-var: 2
  no-eval: 2
  no-undef: 2
  no-undef-init: 2
  no-undefined: 2
  no-new-object: 2
  no-nested-ternary: 2
  no-useless-constructor: 2
  prefer-promise-reject-errors: 2
  prefer-rest-params: 2
  prefer-spread: 2
  quotes: [2, single]
  require-await: 2
  semi: [2, always]
  linebreak-style: [1, unix]
  no-plusplus: 2
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }]
  import/extensions: 0
  typescript-eslint/no-use-before-define": 0
  no-use-before-define: 0
