const MONTHS = {
  JANUARY: 'JANUARY',
  FEBRUARY: 'FEBRUARY',
  MARCH: 'MARCH',
  APRIL: 'APRIL',
  MAY: 'MAY',
  JUNE: 'JUNE',
  JULY: 'JULY',
  AUGUST: 'AUGUST',
  SEPTEMBER: 'SEPTEMBER',
  OCTOBER: 'OCTOBER',
  NOVEMBER: 'NOVEMBER',
  DECEMBER: 'DECEMBER',
};

const MONTH_NUMBER_BY_NAME = {
  [MONTHS.JANUARY]: 1,
  [MONTHS.FEBRUARY]: 2,
  [MONTHS.MARCH]: 3,
  [MONTHS.APRIL]: 4,
  [MONTHS.MAY]: 5,
  [MONTHS.JUNE]: 6,
  [MONTHS.JULY]: 7,
  [MONTHS.AUGUST]: 8,
  [MONTHS.SEPTEMBER]: 9,
  [MONTHS.OCTOBER]: 10,
  [MONTHS.NOVEMBER]: 11,
  [MONTHS.DECEMBER]: 12,
};

const MONTH_NAME_BY_NUMBER = {
  1: MONTHS.JANUARY,
  2: MONTHS.FEBRUARY,
  3: MONTHS.MARCH,
  4: MONTHS.APRIL,
  5: MONTHS.MAY,
  6: MONTHS.JUNE,
  7: MONTHS.JULY,
  8: MONTHS.AUGUST,
  9: MONTHS.SEPTEMBER,
  10: MONTHS.OCTOBER,
  11: MONTHS.NOVEMBER,
  12: MONTHS.DECEMBER,
};

export {
  MONTHS,
  MONTH_NUMBER_BY_NAME,
  MONTH_NAME_BY_NUMBER,
};
