const MONTHS = {
  JANUARY: 'JANUARY',
  FEBRUARY: 'FEBRUARY',
  MARCH: 'MARCH',
  APRIL: 'APRIL',
  MAY: 'MAY',
  JUNE: 'JUNE',
  JULY: 'JULY',
  AUGUST: 'AUGUST',
  SEPTEMBER: 'SEPTEMBER',
  OCTOBER: 'OCTOBER',
  NOVEMBER: 'NOVEMBER',
  DECEMBER: 'DECEMBER',
};

const MONTH_NUMBER_BY_NAME = {
  JANUARY: 1,
  FEBRUARY: 2,
  MARCH: 3,
  APRIL: 4,
  MAY: 5,
  JUNE: 6,
  JULY: 7,
  AUGUST: 8,
  SEPTEMBER: 9,
  OCTOBER: 10,
  NOVEMBER: 11,
  DECEMBER: 12,
};

const MONTH_NAME_BY_NUMBER = {
  1: MONTHS.JANUARY,
  2: MONTHS.FEBRUARY,
  3: MONTHS.MARCH,
  4: MONTHS.APRIL,
  5: MONTHS.MAY,
  6: MONTHS.JUNE,
  7: MONTHS.JULY,
  8: MONTHS.AUGUST,
  9: MONTHS.SEPTEMBER,
  10: MONTHS.OCTOBER,
  11: MONTHS.NOVEMBER,
  12: MONTHS.DECEMBER,
};

export {
  MONTHS,
  MONTH_NUMBER_BY_NAME,
  MONTH_NAME_BY_NUMBER,
};
